//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveUp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MoveUp.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NaviBar_Activities {
            get {
                return ResourceManager.GetString("NaviBar.Activities", resourceCulture);
            }
        }
        
        public static string NaviBar_Friends {
            get {
                return ResourceManager.GetString("NaviBar.Friends", resourceCulture);
            }
        }
        
        public static string NaviBar_Summary {
            get {
                return ResourceManager.GetString("NaviBar.Summary", resourceCulture);
            }
        }
        
        public static string SumView_Calories {
            get {
                return ResourceManager.GetString("SumView.Calories", resourceCulture);
            }
        }
        
        public static string SumView_Floors {
            get {
                return ResourceManager.GetString("SumView.Floors", resourceCulture);
            }
        }
        
        public static string SumView_Header {
            get {
                return ResourceManager.GetString("SumView.Header", resourceCulture);
            }
        }
        
        public static string SumView_Kcal {
            get {
                return ResourceManager.GetString("SumView.Kcal", resourceCulture);
            }
        }
        
        public static string SumView_Km {
            get {
                return ResourceManager.GetString("SumView.Km", resourceCulture);
            }
        }
        
        public static string SumView_Map {
            get {
                return ResourceManager.GetString("SumView.Map", resourceCulture);
            }
        }
        
        public static string SumView_Steps {
            get {
                return ResourceManager.GetString("SumView.Steps", resourceCulture);
            }
        }
        
        public static string SumView_Target {
            get {
                return ResourceManager.GetString("SumView.Target", resourceCulture);
            }
        }
        
        public static string SumView_Walking {
            get {
                return ResourceManager.GetString("SumView.Walking", resourceCulture);
            }
        }
        
        public static string StepsView_Header {
            get {
                return ResourceManager.GetString("StepsView.Header", resourceCulture);
            }
        }
        
        public static string StepsView_SetTarget {
            get {
                return ResourceManager.GetString("StepsView.SetTarget", resourceCulture);
            }
        }
        
        public static string StepsView_WeekHeader {
            get {
                return ResourceManager.GetString("StepsView.WeekHeader", resourceCulture);
            }
        }
        
        public static string StepsView_MonthHeader {
            get {
                return ResourceManager.GetString("StepsView.MonthHeader", resourceCulture);
            }
        }
        
        public static string StepsView_BestDaily {
            get {
                return ResourceManager.GetString("StepsView.BestDaily", resourceCulture);
            }
        }
        
        public static string StepsView_DailyAvg {
            get {
                return ResourceManager.GetString("StepsView.DailyAvg", resourceCulture);
            }
        }
        
        public static string Page_Back {
            get {
                return ResourceManager.GetString("Page.Back", resourceCulture);
            }
        }
        
        public static string StepsView_AllTime {
            get {
                return ResourceManager.GetString("StepsView.AllTime", resourceCulture);
            }
        }
        
        public static string DistanceView_Header {
            get {
                return ResourceManager.GetString("DistanceView.Header", resourceCulture);
            }
        }
        
        public static string FloorsView_Header {
            get {
                return ResourceManager.GetString("FloorsView.Header", resourceCulture);
            }
        }
        
        public static string CaloriesView_Header {
            get {
                return ResourceManager.GetString("CaloriesView.Header", resourceCulture);
            }
        }
        
        public static string Activities_Header {
            get {
                return ResourceManager.GetString("Activities.Header", resourceCulture);
            }
        }
        
        public static string Activities_Hiking {
            get {
                return ResourceManager.GetString("Activities.Hiking", resourceCulture);
            }
        }
        
        public static string Activities_Running {
            get {
                return ResourceManager.GetString("Activities.Running", resourceCulture);
            }
        }
        
        public static string Activities_Cycling {
            get {
                return ResourceManager.GetString("Activities.Cycling", resourceCulture);
            }
        }
        
        public static string Activities_StartNew {
            get {
                return ResourceManager.GetString("Activities.StartNew", resourceCulture);
            }
        }
        
        public static string Activities_Saved {
            get {
                return ResourceManager.GetString("Activities.Saved", resourceCulture);
            }
        }
        
        public static string Activities_Date {
            get {
                return ResourceManager.GetString("Activities.Date", resourceCulture);
            }
        }
        
        public static string Activities_Duration {
            get {
                return ResourceManager.GetString("Activities.Duration", resourceCulture);
            }
        }
        
        public static string Activities_View {
            get {
                return ResourceManager.GetString("Activities.View", resourceCulture);
            }
        }
        
        public static string Activities_Scheduled {
            get {
                return ResourceManager.GetString("Activities.Scheduled", resourceCulture);
            }
        }
        
        public static string Activities_ScheduleOneTime {
            get {
                return ResourceManager.GetString("Activities.ScheduleOneTime", resourceCulture);
            }
        }
        
        public static string Activities_ScheduleRepeating {
            get {
                return ResourceManager.GetString("Activities.ScheduleRepeating", resourceCulture);
            }
        }
        
        public static string Activities_Time {
            get {
                return ResourceManager.GetString("Activities.Time", resourceCulture);
            }
        }
        
        public static string Activities_Delete {
            get {
                return ResourceManager.GetString("Activities.Delete", resourceCulture);
            }
        }
        
        public static string Activities_Start {
            get {
                return ResourceManager.GetString("Activities.Start", resourceCulture);
            }
        }
        
        public static string Activities_Stop {
            get {
                return ResourceManager.GetString("Activities.Stop", resourceCulture);
            }
        }
        
        public static string Activities_Finish {
            get {
                return ResourceManager.GetString("Activities.Finish", resourceCulture);
            }
        }
        
        public static string Activities_Save {
            get {
                return ResourceManager.GetString("Activities.Save", resourceCulture);
            }
        }
        
        public static string Activities_Discard {
            get {
                return ResourceManager.GetString("Activities.Discard", resourceCulture);
            }
        }
        
        public static string Activities_Kmh {
            get {
                return ResourceManager.GetString("Activities.Kmh", resourceCulture);
            }
        }
        
        public static string Activities_Meter {
            get {
                return ResourceManager.GetString("Activities.Meter", resourceCulture);
            }
        }
        
        public static string Hiking_Header {
            get {
                return ResourceManager.GetString("Hiking.Header", resourceCulture);
            }
        }
        
        public static string Hiking_Duration {
            get {
                return ResourceManager.GetString("Hiking.Duration", resourceCulture);
            }
        }
        
        public static string Hiking_Distance {
            get {
                return ResourceManager.GetString("Hiking.Distance", resourceCulture);
            }
        }
        
        public static string Hiking_AvgSpeed {
            get {
                return ResourceManager.GetString("Hiking.AvgSpeed", resourceCulture);
            }
        }
        
        public static string Hiking_Elevation {
            get {
                return ResourceManager.GetString("Hiking.Elevation", resourceCulture);
            }
        }
        
        public static string Hiking_ElevationGain {
            get {
                return ResourceManager.GetString("Hiking.ElevationGain", resourceCulture);
            }
        }
        
        public static string Hiking_Pace {
            get {
                return ResourceManager.GetString("Hiking.Pace", resourceCulture);
            }
        }
        
        public static string Hiking_CurSpeed {
            get {
                return ResourceManager.GetString("Hiking.CurSpeed", resourceCulture);
            }
        }
        
        public static string Hiking_From {
            get {
                return ResourceManager.GetString("Hiking.From", resourceCulture);
            }
        }
        
        public static string Scheduler_Header {
            get {
                return ResourceManager.GetString("Scheduler.Header", resourceCulture);
            }
        }
        
        public static string Scheduler_Pick {
            get {
                return ResourceManager.GetString("Scheduler.Pick", resourceCulture);
            }
        }
        
        public static string Scheduler_ChooseDate {
            get {
                return ResourceManager.GetString("Scheduler.ChooseDate", resourceCulture);
            }
        }
        
        public static string Scheduler_ChooseTime {
            get {
                return ResourceManager.GetString("Scheduler.ChooseTime", resourceCulture);
            }
        }
        
        public static string Scheduler_Notification {
            get {
                return ResourceManager.GetString("Scheduler.Notification", resourceCulture);
            }
        }
        
        public static string Scheduler_Schedule {
            get {
                return ResourceManager.GetString("Scheduler.Schedule", resourceCulture);
            }
        }
        
        public static string Friends_Header {
            get {
                return ResourceManager.GetString("Friends.Header", resourceCulture);
            }
        }
        
        public static string Friends_Link {
            get {
                return ResourceManager.GetString("Friends.Link", resourceCulture);
            }
        }
    }
}
