//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveUp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MoveUp.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NaviBar_Activities {
            get {
                return ResourceManager.GetString("NaviBar.Activities", resourceCulture);
            }
        }
        
        public static string NaviBar_Friends {
            get {
                return ResourceManager.GetString("NaviBar.Friends", resourceCulture);
            }
        }
        
        public static string NaviBar_Summary {
            get {
                return ResourceManager.GetString("NaviBar.Summary", resourceCulture);
            }
        }
        
        public static string SumView_Calories {
            get {
                return ResourceManager.GetString("SumView.Calories", resourceCulture);
            }
        }
        
        public static string SumView_Floors {
            get {
                return ResourceManager.GetString("SumView.Floors", resourceCulture);
            }
        }
        
        public static string SumView_Header {
            get {
                return ResourceManager.GetString("SumView.Header", resourceCulture);
            }
        }
        
        public static string SumView_Kcal {
            get {
                return ResourceManager.GetString("SumView.Kcal", resourceCulture);
            }
        }
        
        public static string SumView_Km {
            get {
                return ResourceManager.GetString("SumView.Km", resourceCulture);
            }
        }
        
        public static string SumView_Map {
            get {
                return ResourceManager.GetString("SumView.Map", resourceCulture);
            }
        }
        
        public static string SumView_Steps {
            get {
                return ResourceManager.GetString("SumView.Steps", resourceCulture);
            }
        }
        
        public static string SumView_Target {
            get {
                return ResourceManager.GetString("SumView.Target", resourceCulture);
            }
        }
        
        public static string SumView_Walking {
            get {
                return ResourceManager.GetString("SumView.Walking", resourceCulture);
            }
        }
        
        public static string StepsView_Header {
            get {
                return ResourceManager.GetString("StepsView.Header", resourceCulture);
            }
        }
        
        public static string StepsView_SetTarget {
            get {
                return ResourceManager.GetString("StepsView.SetTarget", resourceCulture);
            }
        }
        
        public static string StepsView_WeekHeader {
            get {
                return ResourceManager.GetString("StepsView.WeekHeader", resourceCulture);
            }
        }
        
        public static string StepsView_MonthHeader {
            get {
                return ResourceManager.GetString("StepsView.MonthHeader", resourceCulture);
            }
        }
        
        public static string StepsView_BestDaily {
            get {
                return ResourceManager.GetString("StepsView.BestDaily", resourceCulture);
            }
        }
        
        public static string StepsView_AvgWeek {
            get {
                return ResourceManager.GetString("StepsView.AvgWeek", resourceCulture);
            }
        }
        
        public static string StepsView_AvgMonth {
            get {
                return ResourceManager.GetString("StepsView.AvgMonth", resourceCulture);
            }
        }
        
        public static string StepsView_AvgAllTime {
            get {
                return ResourceManager.GetString("StepsView.AvgAllTime", resourceCulture);
            }
        }
        
        public static string Page_Back {
            get {
                return ResourceManager.GetString("Page.Back", resourceCulture);
            }
        }
        
        public static string StepsView_AllTime {
            get {
                return ResourceManager.GetString("StepsView.AllTime", resourceCulture);
            }
        }
    }
}
